#!/usr/bin/env bash
set -e

EMAIL_ADDRESS=$1
if [ ! $# -eq 1 ]; then
  echo "ssu-tx-cashin <email_address>"
  exit 1
elif [[ ! $EMAIL_ADDRESS =~ .+@.+\..+ ]]; then
  echo "Please enter a valid email address."
  echo
  echo "ssu-tx-cashin <email_address>"
  exit 1
fi

if [ $(dpkg-query -W -f='${Status}' mutt 2>/dev/null | grep -c "ok installed") -eq 0 ];
then
  echo "Mutt not installed. Installing..."
  DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes mutt >/dev/null;
fi

IN_TRANSACTIONS_FILE=/tmp/transactions-$HOSTNAME-cash-in-$(date -u "+%Y-%m-%d_%H-%M-%S").csv
su - postgres -c "psql \"lamassu\" -Atc \"COPY cash_in_txs to '$IN_TRANSACTIONS_FILE' WITH CSV HEADER\""
gpg --batch --trust-model always -e -r $EMAIL_ADDRESS $IN_TRANSACTIONS_FILE
rm $IN_TRANSACTIONS_FILE
export EMAIL="Transactions Log <$EMAIL_ADDRESS>"
echo "Attached is your encrypted transactions log." | mutt -s "Encrypted cash-in machine transactions from $HOSTNAME" -a $IN_TRANSACTIONS_FILE.gpg -- $EMAIL_ADDRESS
rm $IN_TRANSACTIONS_FILE.gpg
echo "Transaction log sent to $EMAIL_ADDRESS. If it doesn't appear, check your spam folder."
